name = "termux-tunnel"
main = "worker.js"
compatibility_date = "2024-03-20"

[assets]
directory = "dist"

# Halaman ini sangat penting untuk menghubungkan Worker Anda dengan KV Database.
# Ganti "MASUKKAN_ID_KV_ANDA_DISINI" dengan ID asli dari KV Anda.
[[kv_namespaces]]
binding = "accounts_kv"
id = "fc7e78f9ecec4a4b95fbf4ab82e1e057"
